////////////////////////////////////////////////////////////////////////////////
// ---------- vs_app_setup.h ----------
/*!
\file vs_app_setup.h
\brief Application interface setup
\author Gareth Edwards
\note Generated by app_setup application.
*/


// ---------- #DEFINE ----------
//
// Step 1: Create application #define
//
#define VSX_BMP_UTILITY_01


// ---------- NAME ----------
//
//Included in vsx_sys_windows.cpp
//
// Step 2: Initialise application & development names
//
#ifdef VSX_APPLICATION_APPNAME
{
dev_env.assign("vsx");
app_name.assign("bmp_utility_01");
config_name.assign("bmp_utility_01");
}
#undef VSX_APPLICATION_APPNAME
#endif


// ---------- VERSION ----------
//
//Included in vsx_sys_windows.cpp
//
// Step 3: Include application version info
//
#ifdef VSX_APPLICATION_APPVERSION
{
#include "../../vsx_application/bmp_utility_01/header/bmp1_version.h"
version[0] = VS_APP_VERSION_MAJOR;
version[1] = VS_APP_VERSION_MINOR;
version[2] = VS_APP_VERSION_PATCH;
version[3] = VS_APP_VERSION_BUILD;
}
#undef VSX_APPLICATION_APPVERSION
#endif


// ---------- HEADER ----------
//
//Included in vsx_app_interface.cpp
//
// Step 4: Include application header
//
#ifdef VSX_APPLICATION_INCLUDE
#include "../../vsx_application/bmp_utility_01/header/bmp1_application.h"
#undef VSX_APPLICATION_INCLUDE
#endif


// ---------- SOCKET ----------
//
//Included in vsx_app_interface.cpp
//
// Step 5: Initialise application socket
//
#ifdef VSX_APPLICATION_SOCKET
bmp_utility_01::application *application;
#undef VSX_APPLICATION_SOCKET
#endif


// ---------- POINTER ----------
//
//Included in vsx_app_interface.cpp
//
// Step 6: Initialise application interface
//
#ifdef VSX_APPLICATION_POINTER
if ( app_name.compare("bmp_utility_01") == 0 )
{
socket.application = new bmp_utility_01::application();
ptr_to_framework = &AppInterface::application;;
}
#undef VSX_APPLICATION_POINTER
#endif


