////////////////////////////////////////////////////////////////////////////////
// ---------- vs_app_setup.h ----------
/*!
\file vs_app_setup.h
\brief Application interface setup
\author Gareth Edwards
\note Generated by app_setup application.
*/


// ---------- #DEFINE ----------
//
// Step 1: Create application #define
//
#define VS_SURFACE_03


// ---------- NAME ----------
//
//Included in vs_sys_windows.cpp
//
// Step 2: Initialise application & development names
//
#ifdef VS_APPLICATION_APPNAME
{
dev_env.assign("vs");
app_name.assign("surface_03");
config_name.assign("surface_03");
}
#undef VS_APPLICATION_APPNAME
#endif


// ---------- VERSION ----------
//
//Included in vs_sys_windows.cpp
//
// Step 3: Include application version info
//
#ifdef VS_APPLICATION_APPVERSION
{
#include "../../vs_application/surface_03/header/s3_version.h"
version[0] = VS_APP_VERSION_MAJOR;
version[1] = VS_APP_VERSION_MINOR;
version[2] = VS_APP_VERSION_PATCH;
version[3] = VS_APP_VERSION_BUILD;
}
#undef VS_APPLICATION_APPVERSION
#endif


// ---------- HEADER ----------
//
//Included in vs_app_interface.cpp
//
// Step 4: Include application header
//
#ifdef VS_APPLICATION_INCLUDE
#include "../../vs_application/surface_03/header/s3_application.h"
#undef VS_APPLICATION_INCLUDE
#endif


// ---------- SOCKET ----------
//
//Included in vs_app_interface.cpp
//
// Step 5: Initialise application socket
//
#ifdef VS_APPLICATION_SOCKET
surface_03::application *application;
#undef VS_APPLICATION_SOCKET
#endif


// ---------- POINTER ----------
//
//Included in vs_app_interface.cpp
//
// Step 6: Initialise application interface
//
#ifdef VS_APPLICATION_POINTER
if ( app_name.compare("surface_03") == 0 )
{
socket.application = new surface_03::application();
ptr_to_framework = &AppInterface::application;;
}
#undef VS_APPLICATION_POINTER
#endif


